// treinamentos/React-treinamento/olamundo/src/components/BlogPost/BlogPost.jsx
import React, { useState } from "react";
import "./BlogPost.css";
/**
 * BlogPost Component
 * @param {{post:BlogPostModel}} props
 * @returns
 */
function BlogPost(props) {

  const [contador, setContador] = useState(0);
  const [post, setPost] = useState(props.post);


  function shareClickCallBack() {
    setContador(contador + 1);
  }


  function checkboxChangeBack(event) {
    const novoValorExibirImagem = !post.exibirImagem;
    // verifique o que acontece se não chamarmos o setPost
    // é um erro comum, que você vai fazer bastante
    // precisamos informar a atualização, para o react renderizar novamente
    // https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/Spread_syntax
    setPost({ ...post, exibirImagem: novoValorExibirImagem });
  }

  let imgTag = <div></div>;

  if (post.exibirImagem) {
    imgTag = <img src={post.imagem} alt={post.titulo} />;
  }


  return (
    <article className="blogPost">
      <h2>{post.titulo}</h2>

      <div>
        <input
          type="checkbox"
          defaultChecked={post.exibirImagem}
          onChange={checkboxChangeBack}
        />{" "}
        Exibir imagem?
      </div>
      {imgTag}

      <p>{post.texto}</p>

      <button class="share" onClick={shareClickCallBack}>
        Compartilhar!
      </button>

      <div>Número de vezes que foi compartilhado: {contador}</div>
    </article>
  );

}
export default BlogPost;

// treinamentos/Angular-treinamento/olamundo/src/app/components/blog-post/blog-post.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { BlogPostModel } from '../blog-post-model';
@Component({
  selector: 'app-blog-post',
  templateUrl: './blog-post.component.html',
  styleUrls: ['./blog-post.component.css'],
})

export class BlogPostComponent implements OnInit {
  @Input()
  public post: BlogPostModel = new BlogPostModel();
  public contadorCompartilhar = 0;

  constructor() {
  }

  ngOnInit(): void {
  }

  compartilhar(): void {
    // execute o que quiser aqui.
    // lembre-se que você pode alterar as variaveis locais
    alert('Post ' + this.post?.titulo + ' compartilhado!');
    // desafio contador de compartilhamento
    this.contadorCompartilhar++;
  }
}

<article>
  <h2>{{post?.titulo}}</h2>

  <div>
    <input type="checkbox" [(ngModel)]="post.exibirImagem" /> Exibir imagem?
  </div>

  <img   *ngIf="post.exibirImagem"
    [src]="post?.imagem"
  />

  <p>
    {{post?.texto}}
  </p>

  <button class="share" (click)="compartilhar()">Compartilhar!</button>

  <div>Número de vezes que este post foi compartilhado: {{contadorCompartilhar}}</div>
</article>
